name: Push to NPM registry

on:
    push:
        branches: [master]
permissions:
    contents: write # to be able to publish a GitHub release
    issues: write # to be able to comment on released issues
    pull-requests: write # to be able to comment on released pull requests
    id-token: write # to enable use of OIDC for trusted publishing and npm provenance
jobs:
    deploy-npm:
        name: Deploy to NPM
        runs-on: ubuntu-latest
        container:
            image: node:22-alpine
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm ci

            - name: Lint
              run: npm run lint

            - name: Build package
              run: npm run build:package

            - name: Run unit tests
              run: npm run test:ci

            - name: Run e2e tests
              run: npm run test:e2e:ci

            - name: Release Notes
              run: npm run semantic-release -- -d false --no-ci
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Publish to NPM
              run: npm publish
